%import/include list

import GUI, Card in "../classes/gameCard.t", Deck in "../classes/Deck.t", Column in "../classes/Column.t", Foundation in "../classes/Foundation.t"
include "globalVariables.t"
include "buttonHandlers.t"
include "menu.t"
include "../freecell/drawBoard.t"
include "../klondike/reDraw.t"
include "../freecell/countFreeCell.t"
include "../freecell/storeMove.t"
include "../klondike/storeMove.t"
include "../freecell/fselect.t"
include "../klondike/kselect.t"
include "../freecell/moveStack.t"
include "../klondike/moveStack.t"
include "../freecell/selectStacks.t"
include "../klondike/selectStacks.t"
include "wingame.t"
include "../freecell/freecell.t"
include "../klondike/klondike.t"
